version: '3'
services:
  postgres:
    image: postgres:15
    container_name: citronix-db
    environment:
      POSTGRES_DB: citronix_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Imane2002***
    ports:
      - "5432:5432"
    volumes:
      - citronix-db-data:/var/lib/postgresql/data
    networks:
      - citronix-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: citronix-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/citronix_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Imane2002***
    ports:
      - "8080:8080"
    networks:
      - citronix-network

networks:
  citronix-network:
    driver: bridge

volumes:
  citronix-db-data: